### ISSUE TITLE
Preparation报错

### ISSUE THREAD

**Issue by chadlzx** [CraftJarvis/MC-Planner#1]
很不错的工作，但是在复现时遇到了一些困难，能否帮忙看看呢。

```
python -m pip install git+https://github.com/MineDojo/MineCLIP
```
报错：
```
Collecting git+https://github.com/MineDojo/MineCLIP
  Cloning https://github.com/MineDojo/MineCLIP to c:\users\liuzhixuan\appdata\local\temp\pip-req-build-7dg_y_2b
  Running command git clone --filter=blob:none --quiet https://github.com/MineDojo/MineCLIP 'C:\Users\liuzhixuan\AppData\Local\Temp\pip-req-build-7dg_y_2b'
  Resolved https://github.com/MineDojo/MineCLIP to commit a841322260483c274e1dc09b4e5301ac48cfa4ab
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\liuzhixuan\AppData\Local\Temp\pip-req-build-7dg_y_2b\setup.py", line 38, in <module>
          long_description=_read_file("README.md"),
        File "C:\Users\liuzhixuan\AppData\Local\Temp\pip-req-build-7dg_y_2b\setup.py", line 16, in _read_file
          return fp.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 2022: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```
python -m pip install git+https://github.com/CraftJarvis/MC-Simulator.git
```
报错：
```
Collecting git+https://github.com/CraftJarvis/MC-Simulator.git
  Cloning https://github.com/CraftJarvis/MC-Simulator.git to c:\users\liuzhixuan\appdata\local\temp\pip-req-build-7qi1mrgr
  Running command git clone --filter=blob:none --quiet https://github.com/CraftJarvis/MC-Simulator.git 'C:\Users\liuzhixuan\AppData\Local\Temp\pip-req-build-7qi1mrgr'
  warning: You appear to have cloned an empty repository.
  error: subprocess-exited-with-error

  × git rev-parse HEAD did not run successfully.
  │ exit code: 128
  ╰─> [2 lines of output]
      HEAD
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git rev-parse HEAD did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

windows版本：
```
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎8/‎12
操作系统内部版本	19044.2604
体验	Windows Feature Experience Pack 120.2212.4190.0
```
conda：
```
conda 22.9.0
```

**Comment by zhwang4ai** [comment]
Thanks for your comments.
1. Our code relies on the [MINECLIP](https://github.com/MineDojo/MineCLIP) repo. You can reference this repo to install it.
2. Our agent runs on a modified [Minecraft simulator](https://github.com/CraftJarvis/MC-Simulator). We are still working on open-source it.
3. Lastly, all codes are recommended running on the Ubuntu system. We test on Ubuntu 20.04.

**Comment by chadlzx** [comment]
Thank you for your reply, the problem has been solved after changing the environment to linux.
