### ISSUE TITLE
ModuleNotFoundError: No module named 'tree'

### ISSUE THREAD

**Issue by elegy112138** [CraftJarvis/MC-Planner#14]
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Traceback (most recent call last):
  File "C:\Users\gtc\Desktop\MC-Planner-main\main.py", line 5, in <module>
    from controller import *
  File "C:\Users\gtc\Desktop\MC-Planner-main\controller.py", line 33, in <module>
    from ray.rllib.models.torch.torch_action_dist import TorchMultiCategorical
  File "C:\Users\gtc\AppData\Roaming\Python\Python311\site-packages\ray\rllib\__init__.py", line 7, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "C:\Users\gtc\AppData\Roaming\Python\Python311\site-packages\ray\rllib\env\__init__.py", line 1, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "C:\Users\gtc\AppData\Roaming\Python\Python311\site-packages\ray\rllib\env\base_env.py", line 6, in <module>
    from ray.rllib.utils.annotations import Deprecated, DeveloperAPI, PublicAPI
  File "C:\Users\gtc\AppData\Roaming\Python\Python311\site-packages\ray\rllib\utils\__init__.py", line 6, in <module>
    from ray.rllib.utils.filter import Filter
  File "C:\Users\gtc\AppData\Roaming\Python\Python311\site-packages\ray\rllib\utils\filter.py", line 5, in <module>
    import tree  # pip install dm_tree
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'tree'

**Comment by zhwang4ai** [comment]
You can install this package via `pip install dm_tree`.
