### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Yun-Peng-Wang** [CraftJarvis/MC-Planner#7]
请问这是什么报错，我按照要求把环境装好了，并执行命令`python main.py model.load_ckpt_path=/root/nas/MC/model`
结果报错
Traceback (most recent call last):
  File "/root/nas/MC/MC-Planner/main.py", line 5, in <module>
    from controller import *
  File "/root/nas/MC/MC-Planner/controller.py", line 1, in <module>
    import cv2
  File "/opt/conda/envs/planner/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/envs/planner/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/opt/conda/envs/planner/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by Yun-Peng-Wang** [comment]
pip install opencv-python-headless
